In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.5'

In [3]:
import sys 
sys.version

'3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]'

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list) 

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [ ]:
np.

SyntaxError: invalid syntax (1655120754.py, line 1)

In [11]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(3.0)  

array([0., 1., 2.])

In [13]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(20,10) 

array([], dtype=int64)

In [17]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [19]:
np.arange(-20,-10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [ ]:
np.arange(30,20)  

array([], dtype=int64)

In [21]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [22]:
np.arange(10,10) 

array([], dtype=int64)

In [23]:
np.arange()

TypeError: arange() requires stop to be specified.

In [ ]:
np.arange(10,30,5)  

array([10, 15, 20, 25])

In [25]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [26]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [ ]:
np.zeros(3) 

array([0., 0., 0.])

In [ ]:
np.zeros(5, dtype=int) 

array([0, 0, 0, 0, 0])

In [29]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [30]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [31]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [32]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [ ]:
np.zeros((5,10)) 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) 

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [39]:
n

(6, 7)

In [40]:
n1

(6, 8)

In [41]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [42]:
np.ones(3)

array([1., 1., 1.])

In [43]:
np.ones(4, dtype=int) 

array([1, 1, 1, 1])

In [44]:
np.ones(4)

array([1., 1., 1., 1.])

In [45]:
n

(6, 7)

In [46]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.ones((5,4),dtype=int) 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [48]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [49]:
np.twos((2,3)) 

AttributeError: module 'numpy' has no attribute 'twos'

In [50]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [51]:
np.ones(2)

array([1., 1.])

In [52]:
np.ones((2,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
np.ones((6,10),dtype = int) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [54]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [55]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [56]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

In [57]:
range(5)

range(0, 5)

In [58]:
r = range(5)
r

range(0, 5)

In [59]:
for i in r:
    print(i)

0
1
2
3
4


In [60]:
list(range(5))

[0, 1, 2, 3, 4]

In [61]:
range(1,10)

range(1, 10)

In [62]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [63]:
list(range(1,10,3))

[1, 4, 7]

In [64]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [65]:
rand(3,2)

NameError: name 'rand' is not defined

In [66]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [67]:
np.random.rand(5)

array([0.66719554, 0.06928875, 0.5097096 , 0.39888665, 0.68356015])

In [68]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [69]:
np.random.rand(2,4)

array([[0.03401504, 0.15425658, 0.6446951 , 0.93465966],
       [0.19114269, 0.18166702, 0.69116128, 0.54419999]])

In [70]:
np.random.randint(2,4)

2

In [ ]:
np.random.randint(2,20) 

16

In [72]:
np.random.randint(0,1) 

0

In [73]:
np.random.randint(10,20,5)

array([19, 16, 12, 14, 10], dtype=int32)

In [74]:
np.random.randint(1,6,4)

array([4, 1, 4, 4], dtype=int32)

In [75]:
np.random.rand(3)

array([0.21676669, 0.72458972, 0.01776413])

In [76]:
np.random.randint(1)  

0

In [77]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [78]:
np.random.randint(-30,20,10) 

array([  3, -28,  -1, -10,  -4,   8,  11,  13, -13, -25], dtype=int32)

In [79]:
np.random.randint(20,30,10) 

array([20, 25, 28, 22, 25, 21, 21, 25, 27, 25], dtype=int32)

In [ ]:
np.random.randint(5,9)  

7

In [81]:
np.random.randint(10,21,3)

array([17, 16, 10], dtype=int32)

In [82]:
np.random.randint(1,12,10)

array([ 1,  5,  6,  6, 10,  3,  6,  3,  3,  9], dtype=int32)

In [ ]:
np.random.randint(10,40,(10,10)) 

array([[28, 39, 15, 26, 35, 14, 32, 39, 39, 15],
       [14, 23, 17, 14, 39, 13, 37, 33, 37, 22],
       [22, 23, 38, 36, 27, 36, 11, 21, 13, 22],
       [19, 30, 30, 34, 21, 10, 30, 24, 21, 16],
       [19, 11, 22, 12, 32, 39, 32, 34, 26, 20],
       [24, 39, 31, 29, 23, 16, 10, 20, 36, 21],
       [34, 18, 10, 38, 11, 23, 29, 17, 13, 21],
       [33, 10, 32, 11, 21, 13, 28, 20, 30, 29],
       [16, 22, 22, 21, 24, 34, 20, 24, 20, 35],
       [18, 30, 39, 14, 11, 20, 15, 22, 26, 39]], dtype=int32)

In [ ]:
np.random.randint(1,100,(12,12)) 

array([[99, 39, 88, 40, 19,  9, 23, 87, 64, 81, 91, 98],
       [67,  4, 94, 70, 13, 36, 21, 13, 51, 90, 33, 13],
       [23, 89, 52, 36, 73,  9, 93, 84, 92, 67, 10, 26],
       [35, 19, 69, 50, 37, 85, 46, 33, 67, 76, 80, 55],
       [23, 69, 75, 91, 62, 27, 56, 73, 78, 64, 10, 38],
       [77, 84, 82, 42, 57, 18, 18,  3, 12, 53, 72, 36],
       [87, 62, 37, 56, 61, 58, 20, 14, 82, 98, 94, 31],
       [52, 75, 83, 79, 99, 41, 65, 80, 62, 85, 81, 99],
       [79, 38, 88, 80, 82, 41, 56, 64, 69,  6, 77, 33],
       [25, 15, 19, 77, 35, 81, 95, 37, 27, 14,  4, 64],
       [83, 20, 73, 58, 62, 17, 20,  7, 20, 19, 96, 39],
       [29, 51, 97, 26,  4, 57, 49,  8, 69, 80, 75, 44]], dtype=int32)

In [87]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [89]:
b = np.random.randint(10,20,(5,4))
b

array([[12, 10, 14, 19],
       [19, 17, 14, 17],
       [11, 11, 14, 15],
       [12, 13, 16, 18],
       [18, 12, 19, 11]], dtype=int32)

In [90]:
type(b)

numpy.ndarray

In [91]:
b

array([[12, 10, 14, 19],
       [19, 17, 14, 17],
       [11, 11, 14, 15],
       [12, 13, 16, 18],
       [18, 12, 19, 11]], dtype=int32)

In [92]:
b[:] 

array([[12, 10, 14, 19],
       [19, 17, 14, 17],
       [11, 11, 14, 15],
       [12, 13, 16, 18],
       [18, 12, 19, 11]], dtype=int32)

In [93]:
b[1:3]

array([[19, 17, 14, 17],
       [11, 11, 14, 15]], dtype=int32)

In [94]:
b

array([[12, 10, 14, 19],
       [19, 17, 14, 17],
       [11, 11, 14, 15],
       [12, 13, 16, 18],
       [18, 12, 19, 11]], dtype=int32)

In [95]:
b[1,2]

np.int32(14)

In [96]:
b

array([[12, 10, 14, 19],
       [19, 17, 14, 17],
       [11, 11, 14, 15],
       [12, 13, 16, 18],
       [18, 12, 19, 11]], dtype=int32)

In [97]:
b[1,3]

np.int32(17)

In [98]:
b[1,-1]

np.int32(17)

In [99]:
b

array([[12, 10, 14, 19],
       [19, 17, 14, 17],
       [11, 11, 14, 15],
       [12, 13, 16, 18],
       [18, 12, 19, 11]], dtype=int32)

In [100]:
b[2:3]

array([[11, 11, 14, 15]], dtype=int32)

In [101]:
b

array([[12, 10, 14, 19],
       [19, 17, 14, 17],
       [11, 11, 14, 15],
       [12, 13, 16, 18],
       [18, 12, 19, 11]], dtype=int32)

In [102]:
b[0:-2] 

array([[12, 10, 14, 19],
       [19, 17, 14, 17],
       [11, 11, 14, 15]], dtype=int32)

In [103]:
b

array([[12, 10, 14, 19],
       [19, 17, 14, 17],
       [11, 11, 14, 15],
       [12, 13, 16, 18],
       [18, 12, 19, 11]], dtype=int32)

In [104]:
b[0,2] 

np.int32(14)

In [105]:
b

array([[12, 10, 14, 19],
       [19, 17, 14, 17],
       [11, 11, 14, 15],
       [12, 13, 16, 18],
       [18, 12, 19, 11]], dtype=int32)

In [106]:
b[-5,-3] 

np.int32(10)

In [107]:
b

array([[12, 10, 14, 19],
       [19, 17, 14, 17],
       [11, 11, 14, 15],
       [12, 13, 16, 18],
       [18, 12, 19, 11]], dtype=int32)

In [108]:
b[-4,2] 

np.int32(14)

In [109]:
np.random.randint(10,20,(4,4))

array([[18, 15, 10, 17],
       [15, 16, 14, 18],
       [11, 18, 10, 12],
       [10, 15, 11, 17]], dtype=int32)

In [110]:
b 

array([[12, 10, 14, 19],
       [19, 17, 14, 17],
       [11, 11, 14, 15],
       [12, 13, 16, 18],
       [18, 12, 19, 11]], dtype=int32)

In [111]:
b[-4,-2]

np.int32(14)

In [112]:
b

array([[12, 10, 14, 19],
       [19, 17, 14, 17],
       [11, 11, 14, 15],
       [12, 13, 16, 18],
       [18, 12, 19, 11]], dtype=int32)

In [113]:
b[-4:2] 

array([[19, 17, 14, 17]], dtype=int32)

In [114]:
b[:]

array([[12, 10, 14, 19],
       [19, 17, 14, 17],
       [11, 11, 14, 15],
       [12, 13, 16, 18],
       [18, 12, 19, 11]], dtype=int32)

In [115]:
a = np.random.randint(10,20,10)
a

array([14, 19, 16, 14, 10, 10, 16, 10, 11, 15], dtype=int32)

In [116]:
id(a)

1663091268112

In [117]:
arr

array([0, 1, 2, 3, 4, 5])

In [118]:
arr2 = np.random.randint(0,100,(10,10))

In [119]:
arr2

array([[94, 54, 98, 87, 23, 77, 59, 52,  7, 76],
       [54, 31, 74, 74, 12, 90, 92, 70, 40, 36],
       [ 5, 91, 77, 60,  2, 34, 61, 54, 54, 21],
       [73, 24,  1, 79, 91, 36, 57, 78, 32, 59],
       [78,  9, 83, 56, 64, 82, 73, 93, 12, 47],
       [65, 79, 31, 83, 66, 33, 25, 81, 47, 75],
       [25, 80, 75, 82, 30, 72, 87, 11, 53, 88],
       [ 0, 18, 30, 87,  0, 75, 13, 27, 36, 66],
       [ 8, 76, 52, 43, 17, 31, 42, 83, 63, 60],
       [55, 70, 40, 92, 48, 81,  7, 62, 52, 89]], dtype=int32)

In [120]:
arr

array([0, 1, 2, 3, 4, 5])

In [121]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [122]:
arr

array([0, 1, 2, 3, 4, 5])

In [123]:
arr[:4] 

array([0, 1, 2, 3])

In [124]:
arr2[:]

array([[94, 54, 98, 87, 23, 77, 59, 52,  7, 76],
       [54, 31, 74, 74, 12, 90, 92, 70, 40, 36],
       [ 5, 91, 77, 60,  2, 34, 61, 54, 54, 21],
       [73, 24,  1, 79, 91, 36, 57, 78, 32, 59],
       [78,  9, 83, 56, 64, 82, 73, 93, 12, 47],
       [65, 79, 31, 83, 66, 33, 25, 81, 47, 75],
       [25, 80, 75, 82, 30, 72, 87, 11, 53, 88],
       [ 0, 18, 30, 87,  0, 75, 13, 27, 36, 66],
       [ 8, 76, 52, 43, 17, 31, 42, 83, 63, 60],
       [55, 70, 40, 92, 48, 81,  7, 62, 52, 89]], dtype=int32)

In [125]:
arr2[0:5] 

array([[94, 54, 98, 87, 23, 77, 59, 52,  7, 76],
       [54, 31, 74, 74, 12, 90, 92, 70, 40, 36],
       [ 5, 91, 77, 60,  2, 34, 61, 54, 54, 21],
       [73, 24,  1, 79, 91, 36, 57, 78, 32, 59],
       [78,  9, 83, 56, 64, 82, 73, 93, 12, 47]], dtype=int32)

In [126]:
arr2

array([[94, 54, 98, 87, 23, 77, 59, 52,  7, 76],
       [54, 31, 74, 74, 12, 90, 92, 70, 40, 36],
       [ 5, 91, 77, 60,  2, 34, 61, 54, 54, 21],
       [73, 24,  1, 79, 91, 36, 57, 78, 32, 59],
       [78,  9, 83, 56, 64, 82, 73, 93, 12, 47],
       [65, 79, 31, 83, 66, 33, 25, 81, 47, 75],
       [25, 80, 75, 82, 30, 72, 87, 11, 53, 88],
       [ 0, 18, 30, 87,  0, 75, 13, 27, 36, 66],
       [ 8, 76, 52, 43, 17, 31, 42, 83, 63, 60],
       [55, 70, 40, 92, 48, 81,  7, 62, 52, 89]], dtype=int32)

In [127]:
arr2[1,4] 

np.int32(12)

In [128]:
arr2

array([[94, 54, 98, 87, 23, 77, 59, 52,  7, 76],
       [54, 31, 74, 74, 12, 90, 92, 70, 40, 36],
       [ 5, 91, 77, 60,  2, 34, 61, 54, 54, 21],
       [73, 24,  1, 79, 91, 36, 57, 78, 32, 59],
       [78,  9, 83, 56, 64, 82, 73, 93, 12, 47],
       [65, 79, 31, 83, 66, 33, 25, 81, 47, 75],
       [25, 80, 75, 82, 30, 72, 87, 11, 53, 88],
       [ 0, 18, 30, 87,  0, 75, 13, 27, 36, 66],
       [ 8, 76, 52, 43, 17, 31, 42, 83, 63, 60],
       [55, 70, 40, 92, 48, 81,  7, 62, 52, 89]], dtype=int32)

In [129]:
arr2[-5,5] 

np.int32(33)

In [130]:
arr2[-5,-5] 

np.int32(33)

In [131]:
arr2

array([[94, 54, 98, 87, 23, 77, 59, 52,  7, 76],
       [54, 31, 74, 74, 12, 90, 92, 70, 40, 36],
       [ 5, 91, 77, 60,  2, 34, 61, 54, 54, 21],
       [73, 24,  1, 79, 91, 36, 57, 78, 32, 59],
       [78,  9, 83, 56, 64, 82, 73, 93, 12, 47],
       [65, 79, 31, 83, 66, 33, 25, 81, 47, 75],
       [25, 80, 75, 82, 30, 72, 87, 11, 53, 88],
       [ 0, 18, 30, 87,  0, 75, 13, 27, 36, 66],
       [ 8, 76, 52, 43, 17, 31, 42, 83, 63, 60],
       [55, 70, 40, 92, 48, 81,  7, 62, 52, 89]], dtype=int32)

In [132]:
arr2[-5,-5]

np.int32(33)

In [133]:
arr2

array([[94, 54, 98, 87, 23, 77, 59, 52,  7, 76],
       [54, 31, 74, 74, 12, 90, 92, 70, 40, 36],
       [ 5, 91, 77, 60,  2, 34, 61, 54, 54, 21],
       [73, 24,  1, 79, 91, 36, 57, 78, 32, 59],
       [78,  9, 83, 56, 64, 82, 73, 93, 12, 47],
       [65, 79, 31, 83, 66, 33, 25, 81, 47, 75],
       [25, 80, 75, 82, 30, 72, 87, 11, 53, 88],
       [ 0, 18, 30, 87,  0, 75, 13, 27, 36, 66],
       [ 8, 76, 52, 43, 17, 31, 42, 83, 63, 60],
       [55, 70, 40, 92, 48, 81,  7, 62, 52, 89]], dtype=int32)

In [134]:
arr2[-1,-2]

np.int32(52)

In [135]:
arr2

array([[94, 54, 98, 87, 23, 77, 59, 52,  7, 76],
       [54, 31, 74, 74, 12, 90, 92, 70, 40, 36],
       [ 5, 91, 77, 60,  2, 34, 61, 54, 54, 21],
       [73, 24,  1, 79, 91, 36, 57, 78, 32, 59],
       [78,  9, 83, 56, 64, 82, 73, 93, 12, 47],
       [65, 79, 31, 83, 66, 33, 25, 81, 47, 75],
       [25, 80, 75, 82, 30, 72, 87, 11, 53, 88],
       [ 0, 18, 30, 87,  0, 75, 13, 27, 36, 66],
       [ 8, 76, 52, 43, 17, 31, 42, 83, 63, 60],
       [55, 70, 40, 92, 48, 81,  7, 62, 52, 89]], dtype=int32)

In [136]:
arr2[::-1]

array([[55, 70, 40, 92, 48, 81,  7, 62, 52, 89],
       [ 8, 76, 52, 43, 17, 31, 42, 83, 63, 60],
       [ 0, 18, 30, 87,  0, 75, 13, 27, 36, 66],
       [25, 80, 75, 82, 30, 72, 87, 11, 53, 88],
       [65, 79, 31, 83, 66, 33, 25, 81, 47, 75],
       [78,  9, 83, 56, 64, 82, 73, 93, 12, 47],
       [73, 24,  1, 79, 91, 36, 57, 78, 32, 59],
       [ 5, 91, 77, 60,  2, 34, 61, 54, 54, 21],
       [54, 31, 74, 74, 12, 90, 92, 70, 40, 36],
       [94, 54, 98, 87, 23, 77, 59, 52,  7, 76]], dtype=int32)

In [137]:
arr2

array([[94, 54, 98, 87, 23, 77, 59, 52,  7, 76],
       [54, 31, 74, 74, 12, 90, 92, 70, 40, 36],
       [ 5, 91, 77, 60,  2, 34, 61, 54, 54, 21],
       [73, 24,  1, 79, 91, 36, 57, 78, 32, 59],
       [78,  9, 83, 56, 64, 82, 73, 93, 12, 47],
       [65, 79, 31, 83, 66, 33, 25, 81, 47, 75],
       [25, 80, 75, 82, 30, 72, 87, 11, 53, 88],
       [ 0, 18, 30, 87,  0, 75, 13, 27, 36, 66],
       [ 8, 76, 52, 43, 17, 31, 42, 83, 63, 60],
       [55, 70, 40, 92, 48, 81,  7, 62, 52, 89]], dtype=int32)

In [138]:
arr2[::-2] 

array([[55, 70, 40, 92, 48, 81,  7, 62, 52, 89],
       [ 0, 18, 30, 87,  0, 75, 13, 27, 36, 66],
       [65, 79, 31, 83, 66, 33, 25, 81, 47, 75],
       [73, 24,  1, 79, 91, 36, 57, 78, 32, 59],
       [54, 31, 74, 74, 12, 90, 92, 70, 40, 36]], dtype=int32)

In [139]:
arr2

array([[94, 54, 98, 87, 23, 77, 59, 52,  7, 76],
       [54, 31, 74, 74, 12, 90, 92, 70, 40, 36],
       [ 5, 91, 77, 60,  2, 34, 61, 54, 54, 21],
       [73, 24,  1, 79, 91, 36, 57, 78, 32, 59],
       [78,  9, 83, 56, 64, 82, 73, 93, 12, 47],
       [65, 79, 31, 83, 66, 33, 25, 81, 47, 75],
       [25, 80, 75, 82, 30, 72, 87, 11, 53, 88],
       [ 0, 18, 30, 87,  0, 75, 13, 27, 36, 66],
       [ 8, 76, 52, 43, 17, 31, 42, 83, 63, 60],
       [55, 70, 40, 92, 48, 81,  7, 62, 52, 89]], dtype=int32)

In [140]:
arr2[::-3]

array([[55, 70, 40, 92, 48, 81,  7, 62, 52, 89],
       [25, 80, 75, 82, 30, 72, 87, 11, 53, 88],
       [73, 24,  1, 79, 91, 36, 57, 78, 32, 59],
       [94, 54, 98, 87, 23, 77, 59, 52,  7, 76]], dtype=int32)

In [141]:
arr2

array([[94, 54, 98, 87, 23, 77, 59, 52,  7, 76],
       [54, 31, 74, 74, 12, 90, 92, 70, 40, 36],
       [ 5, 91, 77, 60,  2, 34, 61, 54, 54, 21],
       [73, 24,  1, 79, 91, 36, 57, 78, 32, 59],
       [78,  9, 83, 56, 64, 82, 73, 93, 12, 47],
       [65, 79, 31, 83, 66, 33, 25, 81, 47, 75],
       [25, 80, 75, 82, 30, 72, 87, 11, 53, 88],
       [ 0, 18, 30, 87,  0, 75, 13, 27, 36, 66],
       [ 8, 76, 52, 43, 17, 31, 42, 83, 63, 60],
       [55, 70, 40, 92, 48, 81,  7, 62, 52, 89]], dtype=int32)

In [142]:
arr2[:-3] 

array([[94, 54, 98, 87, 23, 77, 59, 52,  7, 76],
       [54, 31, 74, 74, 12, 90, 92, 70, 40, 36],
       [ 5, 91, 77, 60,  2, 34, 61, 54, 54, 21],
       [73, 24,  1, 79, 91, 36, 57, 78, 32, 59],
       [78,  9, 83, 56, 64, 82, 73, 93, 12, 47],
       [65, 79, 31, 83, 66, 33, 25, 81, 47, 75],
       [25, 80, 75, 82, 30, 72, 87, 11, 53, 88]], dtype=int32)

In [143]:
arr

array([0, 1, 2, 3, 4, 5])

In [144]:
arr.max() 

np.int64(5)

In [145]:
arr.min()

np.int64(0)

In [146]:
arr

array([0, 1, 2, 3, 4, 5])

In [147]:
arr.mean()

np.float64(2.5)

In [148]:
arr

array([0, 1, 2, 3, 4, 5])

In [149]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [150]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

In [151]:
arr

array([0, 1, 2, 3, 4, 5])

In [152]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

In [153]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [154]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [155]:
arr

array([0, 1, 2, 3, 4, 5])

In [156]:
arr.reshape(2,4) 

ValueError: cannot reshape array of size 6 into shape (2,4)

In [157]:
arr

array([0, 1, 2, 3, 4, 5])

In [158]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.reshape(2,3,order='F') 

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
arr.reshape(2,3,order='A') 

array([[0, 1, 2],
       [3, 4, 5]])

In [161]:
arr

array([0, 1, 2, 3, 4, 5])

In [162]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [163]:
arr.reshape(1,4)  

ValueError: cannot reshape array of size 6 into shape (1,4)

In [164]:
arr.reshape(1,6)  

array([[0, 1, 2, 3, 4, 5]])

In [165]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [166]:
arr.reshape(2,6) 

ValueError: cannot reshape array of size 6 into shape (2,6)

In [167]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 6 into shape (3,3)

In [168]:
arr

array([0, 1, 2, 3, 4, 5])

In [169]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

In [170]:
mat = np.arange(0,100).reshape(10,10) 

In [171]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [172]:
row = 4
col = 5

In [173]:
col

5

In [174]:
row

4

In [175]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [176]:
mat[row,col] 

np.int64(45)

In [177]:
mat[4,5] 

np.int64(45)

In [178]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [179]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [180]:
col = 6

In [181]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[6] 

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [183]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [185]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [186]:
mat[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [187]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [188]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [189]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [190]:
mat[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [191]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [192]:
row

4

In [193]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [194]:
mat[:row]  

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [195]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [196]:
mat[row:] 

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [197]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [198]:
mat[:,8] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [199]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [200]:
mat[:,-1] 

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [201]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [202]:
row

4

In [203]:
col

6

In [204]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [205]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [206]:
mat[1,4]

np.int64(14)

In [207]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [208]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [209]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [210]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [211]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [212]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [213]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [214]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [215]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [216]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [217]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [218]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [219]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [220]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [221]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [222]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [223]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [224]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [225]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [226]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [227]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [228]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [229]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [230]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [231]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [232]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [233]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [234]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [235]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [236]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [237]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [238]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [239]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [241]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [242]:
mat[0,1]

np.int64(1)

In [243]:
mat[1,6]

np.int64(16)

In [244]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [245]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [246]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [247]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [248]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [249]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [250]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [251]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [252]:
mat[3,5]

np.int64(35)

In [253]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [254]:
mat[1:2,2:4] 

array([[12, 13]])

In [255]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [256]:
mat[2:3,2:3] 

array([[22]])

In [257]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [258]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [259]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [260]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [261]:
mat[2:3,4:5]

array([[24]])

In [ ]:
mat 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [263]:
id(mat)

1663481173776

In [264]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [265]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [266]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [267]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [268]:
mat[mat==50] 

array([50])

In [269]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [270]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [271]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [272]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [273]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [274]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [275]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [276]:
a4 = mat[mat==50]
a4

array([50])

In [ ]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

otp_length = 4  
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 0323


In [278]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [279]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [280]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x000001834F350440>


In [281]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
